repos:
  - repo: https://github.com/timothycrosley/isort
    rev: "5.3.0"
    hooks:
      - id: isort
        args: [--settings=pyproject.toml]
  - repo: https://github.com/psf/black
    rev: "19.10b0"
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3"
    hooks:
      - id: flake8
        args: [--config=.flake8]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        args: [--config=.pydocstyle.ini]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
