version: 2

python:
  version: "3.7"
  install:
    - requirements: requirements-dev.txt
    - requirements: requirements-pytorch-rtd.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats: all
