name: publishable

on:
  push:
    branches:
      - main
      - releases/*

  pull_request:

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env

      - name: Check if publishable
        run: doit publishable
