name: publish

on:
  release:
    types:
      - published

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade and install additional system packages
        run: pip install --upgrade setuptools virtualenv wheel

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env

      - name: Publish to PyPI
        env:
          TWINE_REPOSITORY: pypi
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: doit publish
