name: tests

on:
  pull_request:
    paths:
      - "tests/download/**"
      - ".github/workflows/tests-download.yml"

  schedule:
    - cron: "0 4 * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade and install additional system packages
        run: pip install --upgrade setuptools virtualenv wheel

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt
        
      - name: Create environment
        run: tox -e tests-download --notest

      - name: Run tests
        run: tox -e tests-download -- tests/download

      - uses: JasonEtco/create-an-issue@v2.4.0
          if: ${{ failure() }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO: ${{ github.repository }}
            WORKFLOW: ${{ github.workflow }}
            JOB: ${{ github.job }}
            ID: ${{ github.run_id }}
          with:
            filename: .github/failed_schedule_issue_template.md
